version: '3'
services:
  dev:
    image: node:11
    volumes:
      - .:/usr/src/service  
      - :/usr/src/service/node_modules
    working_dir: /usr/src/service
    command: npm run dev
    ports:
      - 1234:1234
      - 1235:1235
